# Uncomment this line to define a global platform for your project
# platform :ios, '8.0'
# Uncomment this line if you're using Swift
# use_frameworks!

target 'PaypalDemo' do
pod 'PayPal-iOS-SDK',  '2.14.2'

end

